// Regenerates assets.js from the creator web app, so the brand app reuses the exact same design assets.
//   const A     – images (campaign photos, brand logos, avatars)
//   const ICON  – card / nav icons
//   const CPICON – campaign-page icons
//   const MICON – header icons (search, bell)
// Only the keys the brand app uses are copied, to keep the page light.
// Usage: node scripts/sync-assets.js <path-to-creator-web-app>
const fs = require('fs');
const path = require('path');
const vm = require('vm');

const creator = process.argv[2];
if (!creator) { console.error('Usage: node scripts/sync-assets.js <path-to-creator-web-app>'); process.exit(1); }
const mobile = fs.readFileSync(path.join(creator, 'prototype (1).html'), 'utf8');

function block(start) {
  const i = mobile.indexOf(start);
  if (i < 0) throw new Error(`"${start}" not found in the mobile prototype`);
  const end = mobile.indexOf('\n};', i);
  if (end < 0) throw new Error(`No closing "};" for "${start}"`);
  return mobile.slice(i, end + 3);
}
function svgAfter(marker, from = 0) {
  const i = mobile.indexOf(marker, from);
  if (i < 0) throw new Error(`Icon marker "${marker}" not found in the mobile prototype`);
  const s = mobile.indexOf('<svg', i);
  const e = mobile.indexOf('</svg>', s);
  return mobile.slice(s, e + 6).replace(/\s*\n\s*/g, ' ');
}
function pick(obj, keys, name) {
  const out = {};
  for (const k of keys) { if (!(k in obj)) throw new Error(`${name}.${k} missing`); out[k] = obj[k]; }
  return out;
}

const ctx = {};
vm.runInNewContext(`${block('const A = {')}\n${block('const ICON = {')}\n${block('const CPICON={')}\nthis.A=A;this.ICON=ICON;this.CPICON=CPICON;`, ctx);

const A = pick(ctx.A, [
  'card1', 'card2', 'card3', 'sbHero', 'burgerPhoto', 'grid2', 'grid3', 'grid6', // campaign photos
  'logo1', 'logo2', 'logo3', 'starbucks', 'burgerking', 'dominos',      // brand logos
  'avatar', 'pfAvatar', 'pickmeLogo', 'uberLogo', 'legoLogo', 'pepsi',  // header + notifications
  'av1', 'av2', 'av3', 'av4',                                            // creator avatars
], 'A');
const ICON = pick(ctx.ICON, ['explore', 'heart', 'tiktok', 'insta', 'user'], 'ICON');
const home = mobile.indexOf('id="home"');
const MICON = {
  search: svgAfter('<div class="right">', home),
  bell: svgAfter('data-nav="notifications"', home),
};

const js = `/* Generated by scripts/sync-assets.js from the creator web app — do not edit by hand. */
const A = ${JSON.stringify(A, null, 1)};
const ICON = ${JSON.stringify(ICON, null, 1)};
const CPICON = ${JSON.stringify(ctx.CPICON, null, 1)};
const MICON = ${JSON.stringify(MICON, null, 1)};
`;
const outFile = path.join(__dirname, '..', 'assets.js');
fs.writeFileSync(outFile, js);
console.log(`assets.js written (${(js.length / 1024).toFixed(0)} KB)`);
